sudo: false

language: php

branches:
  except:
    - /^\d+\.\d+\.\d+/

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
      env:
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true
    - php: 7
    - php: hhvm 
  allow_failures:
    - php: 7
    - php: hhvm

before_install:
  - phpenv config-rm xdebug.ini || return 0
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - ./vendor/bin/phpunit
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs ; fi

notifications:
  irc: "irc.freenode.org#apigility-dev"
  email: false
